"""Add correlation_id

Revision ID: 5d113bd4d9e3
Revises: 62a050e24aff
Create Date: 2026-08-29 14:34:17.349413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d113bd4d9e3'
down_revision: Union[str, Sequence[str], None] = '62a050e24aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.add_column('alerts', sa.Column('correlation_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_alerts_correlation_id'), 'alerts', ['correlation_id'], unique=False)
    op.add_column('incidents', sa.Column('correlation_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_incidents_correlation_id'), 'incidents', ['correlation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_correlation_id'), table_name='incidents')
    op.drop_column('incidents', 'correlation_id')
    op.drop_index(op.f('ix_alerts_correlation_id'), table_name='alerts')
    op.drop_column('alerts', 'correlation_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
