"""Add ML tracking fields

Revision ID: 62a050e24aff
Revises: 14ad521e6b16
Create Date: 2026-08-29 10:57:52.666314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a050e24aff'
down_revision: Union[str, Sequence[str], None] = '14ad521e6b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('model_version', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('ml_available', sa.Boolean(), nullable=True))
    op.add_column('alerts', sa.Column('processing_latency', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'processing_latency')
    op.drop_column('alerts', 'ml_available')
    op.drop_column('alerts', 'model_version')
    # ### end Alembic commands ###
