"""
UniShield AI — Prometheus Metrics
===================================
Centralized Prometheus metrics registry for the SOC platform.
All metrics must use runtime measurements. High cardinality labels
(e.g., source_ip, correlation_id) are strictly prohibited.
"""

from prometheus_client import Counter, Histogram, Gauge

# ----------------------------------------------------------------
# INGESTION
# ----------------------------------------------------------------
INGESTION_EVENTS_TOTAL = Counter(
    "unishield_ingestion_events_total",
    "Total number of events read from ingestion source",
    ["source_type"]
)
INGESTION_ERRORS_TOTAL = Counter(
    "unishield_ingestion_errors_total",
    "Total ingestion errors",
    ["source_type"]
)
INGESTION_LATE_EVENTS_TOTAL = Counter(
    "unishield_ingestion_late_events_total",
    "Events arriving out of watermarked time window",
    ["source_type"]
)
INGESTION_QUEUE_DEPTH = Gauge(
    "unishield_ingestion_queue_depth",
    "Current depth of the ingestion/flow queues",
    ["queue_name"]
)
INGESTION_DROPPED_TOTAL = Counter(
    "unishield_ingestion_events_dropped_total",
    "Events dropped due to full queues",
    ["queue_name"]
)

# ----------------------------------------------------------------
# PIPELINE
# ----------------------------------------------------------------
PIPELINE_EVENTS_PROCESSED_TOTAL = Counter(
    "unishield_pipeline_events_processed_total",
    "Total flows/events processed by the main pipeline",
    ["stage"]
)
PIPELINE_ERRORS_TOTAL = Counter(
    "unishield_pipeline_processing_errors_total",
    "Errors during pipeline processing",
    ["stage"]
)
PIPELINE_LATENCY_SECONDS = Histogram(
    "unishield_pipeline_latency_seconds",
    "End-to-end processing latency from ingestion to persistence",
    buckets=[0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0]
)

# ----------------------------------------------------------------
# DETECTORS
# ----------------------------------------------------------------
DETECTOR_INVOCATIONS_TOTAL = Counter(
    "unishield_detector_invocations_total",
    "Total times a detector was invoked",
    ["detector"]
)
DETECTOR_ALERTS_TOTAL = Counter(
    "unishield_detector_alerts_total",
    "Total alerts generated by a detector",
    ["detector", "threat_class"]
)
DETECTOR_ERRORS_TOTAL = Counter(
    "unishield_detector_errors_total",
    "Errors isolated within a specific detector",
    ["detector"]
)
DETECTOR_LATENCY_SECONDS = Histogram(
    "unishield_detector_latency_seconds",
    "Processing latency per detector",
    ["detector"],
    buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0]
)

# ----------------------------------------------------------------
# ML MODELS
# ----------------------------------------------------------------
MODEL_INFERENCE_TOTAL = Counter(
    "unishield_model_inference_total",
    "Total ML inferences attempted",
    ["model_name"]
)
MODEL_INFERENCE_ERRORS_TOTAL = Counter(
    "unishield_model_inference_errors_total",
    "Total ML inference errors",
    ["model_name"]
)
MODEL_FALLBACK_TOTAL = Counter(
    "unishield_model_fallback_total",
    "Times the statistical fallback was used instead of ML",
    ["model_name"]
)
MODEL_INFERENCE_LATENCY_SECONDS = Histogram(
    "unishield_model_inference_latency_seconds",
    "ML inference latency",
    ["model_name"],
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0]
)

# ----------------------------------------------------------------
# CORRELATION & RISK
# ----------------------------------------------------------------
CORRELATION_ALERTS_TOTAL = Counter(
    "unishield_correlation_alerts_total",
    "Alerts processed by correlation engine"
)
CORRELATION_INCIDENTS_TOTAL = Counter(
    "unishield_correlation_incidents_total",
    "Incidents created or updated"
)
CORRELATION_ERRORS_TOTAL = Counter(
    "unishield_correlation_errors_total",
    "Errors during alert correlation"
)

RISK_EVALUATIONS_TOTAL = Counter(
    "unishield_risk_evaluations_total",
    "Risk evaluations performed"
)
RISK_ERRORS_TOTAL = Counter(
    "unishield_risk_errors_total",
    "Errors during risk evaluation"
)

# ----------------------------------------------------------------
# DATABASE & REDIS
# ----------------------------------------------------------------
DATABASE_OPERATIONS_TOTAL = Counter(
    "unishield_database_operations_total",
    "PostgreSQL operations executed",
    ["operation"] # e.g. 'insert_alert', 'update_incident'
)
DATABASE_ERRORS_TOTAL = Counter(
    "unishield_database_errors_total",
    "PostgreSQL operation errors",
    ["operation"]
)
DATABASE_LATENCY_SECONDS = Histogram(
    "unishield_database_latency_seconds",
    "PostgreSQL operation latency",
    ["operation"],
    buckets=[0.005, 0.01, 0.05, 0.1, 0.5, 1.0]
)

REDIS_OPERATIONS_TOTAL = Counter(
    "unishield_redis_operations_total",
    "Redis operations executed",
    ["operation"]
)
REDIS_ERRORS_TOTAL = Counter(
    "unishield_redis_errors_total",
    "Redis operation errors",
    ["operation"]
)
REDIS_LATENCY_SECONDS = Histogram(
    "unishield_redis_latency_seconds",
    "Redis operation latency",
    ["operation"],
    buckets=[0.001, 0.005, 0.01, 0.05, 0.1, 0.5]
)

# ----------------------------------------------------------------
# HTTP API
# ----------------------------------------------------------------
HTTP_REQUESTS_TOTAL = Counter(
    "unishield_http_requests_total",
    "Total HTTP requests to the API",
    ["method", "endpoint", "status_code"]
)
HTTP_REQUEST_ERRORS_TOTAL = Counter(
    "unishield_http_request_errors_total",
    "HTTP 5xx errors",
    ["method", "endpoint"]
)
HTTP_REQUEST_LATENCY_SECONDS = Histogram(
    "unishield_http_request_latency_seconds",
    "HTTP request processing latency",
    ["method", "endpoint"],
    buckets=[0.01, 0.05, 0.1, 0.5, 1.0, 5.0]
)
